### ISSUE TITLE
Run the Project in Visual Studio 2012

### ISSUE THREAD

**Issue by Tochemey** [jgauffin/griffin.networking#13]
I downloaded the project. Anytime I want to load the project in Visual Studio 2012 all the sub projects in the protocols folder load properly except the FREESWITCH sub project. However the reason I am showing interest to the project is the FREESWITCH sub project. Please I would like someone to assist me fix this. I think I am missing something.

Thank you.

**Comment by jgauffin** [comment]
I have changed the core library a lot and have not used FS in a while. Feel free to fix the FreeSwitch library as I won't do it anytime soon.

**Comment by Tochemey** [comment]
Thank you. I will try my best.

**Comment by MrGab** [comment]
Hi Tochemey, 

I'm interested too, could you possibly resolve that?

Thanks in advice 
Gabriele

**Comment by Tochemey** [comment]
I am able to run the whole code base in Visual studio.
