### ISSUE TITLE
HttpRequest / ProduceGoodUri issue

### ISSUE THREAD

**Issue by wo80** [jgauffin/griffin.networking#25]
Though commit b7bbc67916f1598e38f6b7cc43a7249397a4369f fixes the exception, the problem mentioned in issue #23 remains. 

Example:
1. Request is `http://127.0.0.1/a/b/test.html`
2. Now we're in the HttpRequest constructor:
- Uri = ProduceGoodUri("/a/b/test.html") = ["http://a/b/test.html"]
- _pathAndQuery = Uri.PathAndQuery = ["/b/test.html"]

So `http://127.0.0.1/b/test.html` gets served (note the missing "/a" part).

**Comment by hultqvist** [comment]
I've suggested one fix in #26 does that work for you?

**Comment by wo80** [comment]
Yes. Thanks for your contributions!
