### ISSUE TITLE
Null reference....

### ISSUE THREAD

**Issue by dazoe** [jgauffin/griffin.networking#4]
I tried out your library to use the http server... and noticed it fails on http 1.0 requests.

**Comment by jgauffin** [comment]
Can you provide a failing request?

**Comment by dazoe** [comment]
GET / HTTP/1.0
Host: blue:8888
Connection: Keep-Alive
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Language: en-US,en;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3

**Comment by jgauffin** [comment]
the parser itself works. Just added a unit test with that request.

Can you include the exception details?

**Comment by dazoe** [comment]
Sorry, for the long delay. I believe the problem is with Ad Muncher. When I disable Ad Muncher the problem goes away. If i have some time this afternoon I'll recreate the bug and get the exception details.

**Comment by jgauffin** [comment]
Did you have a chance to reproduce it?

**Comment by dazoe** [comment]
For some reason my debugger is not catching the exception. But there is a null reference at line 223 in ServerClientContext.cs

```
                bool isPending = _socket.ReceiveAsync(_readArgs);
```

_socket is null.
I think what is happening here is AdMuncher is closing the connection immediately after the content is received.

**Comment by jgauffin** [comment]
Fixed in the next commit.
