### ISSUE TITLE
IMessageBuilder reused without initialization.

### ISSUE THREAD

**Issue by yjchun** [jgauffin/griffin.networking#5]
MessageClientContext is preallocated by server and reused when client connects.
IMessageBuilder is reused by MessageClientContext  eventually.

If IMessageBuilder has any state machine in it (like in my server...) It fails to work once it is reused.
I can find no easy workaround for this problem.

I would expect IMessageFormatterFactory.CreateBuilder() is called every time client is connected.

**Comment by jgauffin** [comment]
Good point. I'll implement it
