### ISSUE TITLE
No RemoteEndPoint in HTTP request.

### ISSUE THREAD

**Issue by dr4cul4** [jgauffin/griffin.networking#7]
Please fix that.

Class: Griffin.Networking.Protocol.Http.Pipeline.Handlers.HeaderDecoder
Method: void HandleUpstream(IPipelineHandlerContext, IPipelineMessage)

After line:
    var recivedHttpMsg = new ReceivedHttpRequest((IRequest)_message);

Add:
    ((HttpRequest)recivedHttpMsg.HttpRequest).RemoteEndPoint = msg.RemoteEndPoint as System.Net.IPEndPoint;

This solves issue.

**Comment by jgauffin** [comment]
fixed in the next commit
